stages:
    - build
    - d-build
    - deploy

maven-build:
    stage: build
    image: maven:latest
    script:
        - mvn clean compile
        - mvn package -B -DskipTests=true
    artifacts:
        paths:
            - target/*.jar

docker-build:
    stage: d-build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE .
        - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE
        - docker logout
        
aws-prod:
    stage: deploy
    image: docker:latest
    services:
        - docker:dind
    script:
        - if ["$(docker -H $SPRING_CLUSTER ps)"]; then docker -H $SPRING_CLUSTER stop $(docker ps -q); else echo "No container up"; fi
        - if ["$(docker -H $SPRING_CLUSTER ps -a)"]; then docker -H $SPRING_CLUSTER container prune -f; else echo "No container down"; fi
        - if ["$(docker -H $SPRING_CLUSTER images)"]; then docker -H $SPRING_CLUSTER image prune -a -f; else echo "No image"; fi
        - docker -H $SPRING_CLUSTER pull $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE
        - docker -H $SPRING_CLUSTER run --network dbconnection -p 80:3002 -e DATABASE_URI=performawsrds.cub35eckpmbo.eu-west-3.rds.amazonaws.com -e DBUSER=admin -e DBPASSWORD=Pokerface2371984 -e DBNAME=performdb -d $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE
    rules:
        - when: manual

