stages:
    - build
    - d-build

maven-build:
    stage: build
    image: maven:latest
    script:
        - mvn clean compile
        - mvn -DATABASE_URI=$DATABASE_URI -DBUSER=$DBUSER -DBPASSWORD=$DBPASSWORD package -B -DskipTests=true
    artifacts:
        paths:
            - target/*.jar

docker-build:
    stage: d-build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
        - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE .
        - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_IMAGE
        - docker logout