stages:
    - build
    - deploy-on-s3
    - deploy-on-eb

maven-build:
    stage: build
    image: maven:latest
    script:
        - mvn clean compile
        - mvn package -B -DskipTests=true
    artifacts:
        paths:
            - target/*.jar

aws-s3:
    stage: deploy-on-s3
    image: python:latest
    services:
        - docker:dind
    script:
        - apt-get update -qy
        - apt-get install -y awscli
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws s3 cp target/*.jar s3://$S3_NAME/
        
aws-eb:
    stage: deploy-on-eb
    image: python:latest
    services:
        - docker:dind
    script:
        - apt-get update -qy
        - apt-get install -y awscli
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws elasticbeanstalk create-application-version --region $AWS_REGION --application-name $EB_APP_NAME --version-label ${CI_COMMIT_SHA:0:7} --source-bundle S3Bucket=$S3_NAME,S3Key=$JAR_FILE
        - aws elasticbeanstalk update-environment --region $AWS_REGION --application-name $EB_APP_NAME --environment-name $EB_ENV_NAME --version-label ${CI_COMMIT_SHA:0:7} 
        - aws elasticbeanstalk restart-app-server --environment-name $EB_ENV_NAME --version-label ${CI_COMMIT_SHA:0:7}
    rules:
        - when: manual