stages:
    - build
    - deploy

maven-build:
    stage: build
    image: maven:latest
    script:
        - mvn clean compile
        - mvn package -B -DskipTests=true
    artifacts:
        paths:
            - target/*.jar
        
aws-spring:
    stage: deploy
    image: python:latest
    services:
        - docker:dind
    script:
        - apt-get update -qy
        - apt-get install -y awscli
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws elasticbeanstalk create-application-version --application-name perfmma-eb --version-label <VOTRE_VERSION> --source-bundle S3Bucket=elasticbeanstalk-eu-west-3-922861330522,S3Key=target/*.jar
        - aws elasticbeanstalk update-environment --region $AWS_REGION --application-name perfmma-eb --environment-name Perfmma-eb-env
        - aws elasticbeanstalk restart-app-server --environment-name Perfmma-eb-env
    rules:
        - when: manual