stages:
    - build
    - deploy

maven-build:
    stage: build
    image: maven:latest
    script:
        - mvn clean compile
        - mvn package -B -DskipTests=true
    artifacts:
        paths:
            - target/*.jar
        
aws-spring:
    stage: deploy
    image: python:latest
    services:
        - docker:dind
    script:
        - apt-get update -qy
        - apt-get install -y awscli
        - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        - aws s3 cp target/perform-back-spring-0.0.1-SNAPSHOT.jar s3://perform-spring/
    rules:
        - when: manual